[config]
model = "gpt-4"
model_turbo = "gpt-4-turbo"
# 日本語にならなかったので、まだ使用できなさそう
# model = "gpt-4o"
# model_turbo = "gpt-4o"

[pr_reviewer]
extra_instructions = """\
日本語で返答してください。

レビューに必要な観点###
- 一般的なプログラミング原則に沿うこと
- 以下の文書で示されている方針に沿うこと
  - https://www.swift.org/documentation/api-design-guidelines/
###
"""

[pr_description]
publish_labels = false
# use_description_markers = true
extra_instructions = """\
日本語で返答してください。
"""
